export const GET_GENRES = 'GENRES::GET';
export const GET_GENRES_SUCCESS = 'GENRES::GET_SUCCESS';
export const GET_GENRES_FAILURE = 'GENRES::GET_FAILURE';
export const SET_FILTER_GENRE = 'GENRES::SET_FILTER';
