export const GET_MOVIES = 'MOVIES::GET';
export const GET_MOVIES_SUCCESS = 'MOVIES::GET_SUCCESS';
export const GET_MOVIES_FAILURE = 'MOVIES::GET_FAILURE';
export const FILTER_MOVIE_RATING = 'MOVIES::FILTER_RATING';
